var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/tasks/[clientArtifactId]/route.js")
R.c("server/chunks/[root-of-the-server]__03itjmr._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_05__mqx._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0c_d7i~._.js")
R.c("server/chunks/[root-of-the-server]__00dj831._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0mgx._s._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/023u_app_api_projects_[projectId]_tasks_[clientArtifactId]_route_actions_0_vwhck.js")
R.m(762414)
module.exports=R.m(762414).exports
