var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/usage/route.js")
R.c("server/chunks/[root-of-the-server]__06c-yn-._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0mgx._s._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/0d7q__next-internal_server_app_api_projects_[projectId]_usage_route_actions_0rx~7oh.js")
R.m(739309)
module.exports=R.m(739309).exports
