var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/brief/route.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0nhhi.u._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0c_d7i~._.js")
R.c("server/chunks/[root-of-the-server]__11v23j9._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_071t7sf._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0kkr2oe._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0v~25-e._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_04~r269._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0mgx._s._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_journey_0~y2qc1._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/[root-of-the-server]__00dj831._.js")
R.c("server/chunks/0d7q__next-internal_server_app_api_projects_[projectId]_brief_route_actions_13yf_f3.js")
R.m(596721)
module.exports=R.m(596721).exports
