var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/interviews/route.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_10ncx-s._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0c_d7i~._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_journey_0~y2qc1._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/[root-of-the-server]__0v5aogq._.js")
R.c("server/chunks/[root-of-the-server]__00dj831._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0mgx._s._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_071t7sf._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/02nj_server_app_api_projects_[projectId]_interviews_route_actions_0drenzo.js")
R.m(528372)
module.exports=R.m(528372).exports
