var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/context/route.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0yvwu_g._.js")
R.c("server/chunks/[root-of-the-server]__07dzpe6._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0mgx._s._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0c_d7i~._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0~rx_r0._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/[root-of-the-server]__00dj831._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_ecosystem-monitors_ts_02683or._.js")
R.c("server/chunks/11xl_next-internal_server_app_api_projects_[projectId]_context_route_actions_00tq5.w.js")
R.m(226802)
module.exports=R.m(226802).exports
