var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/demo/inbox/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lv80zs._.js")
R.c("server/chunks/ssr/0mjv_0r4df3j._.js")
R.c("server/chunks/ssr/0mjv_next_dist_esm_build_templates_app-page_095cplc.js")
R.c("server/chunks/ssr/[root-of-the-server]__062ywqe._.js")
R.c("server/chunks/ssr/0mjv_next_dist_0_937wb._.js")
R.c("server/chunks/ssr/0mjv_next_dist_shared_lib_invariant-error_0fv1gms.js")
R.c("server/chunks/ssr/0mjv_next_dist_114qhps._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xf76wi._.js")
R.c("server/chunks/ssr/tech-bricks_LaunchPad-v2_src_app_error_tsx_0tl_efy._.js")
R.c("server/chunks/ssr/tech-bricks_LaunchPad-v2_src_app_not-found_tsx_02rihr.._.js")
R.c("server/chunks/ssr/0mjv_next_dist_client_components_0bp4kus._.js")
R.c("server/chunks/ssr/0mjv_next_dist_client_components_builtin_unauthorized_08sm3~u.js")
R.c("server/chunks/ssr/0mjv_next_dist_client_components_builtin_global-error_0xroybp.js")
R.c("server/chunks/ssr/tech-bricks_LaunchPad-v2_src_app_demo_layout_tsx_0x3t8d6._.js")
R.c("server/chunks/ssr/0jef_LaunchPad-v2__next-internal_server_app_demo_inbox_page_actions_0ni370x.js")
R.m(998259)
module.exports=R.m(998259).exports
