var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/knowledge/upload/route.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_02r6d0k._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_journey_0~y2qc1._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0c_d7i~._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_01d6ryd._.js")
R.c("server/chunks/[root-of-the-server]__03rm1g9._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0mgx._s._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/0mjv_0yf2dbb._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/[root-of-the-server]__00dj831._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0mlx.s7._.js")
R.c("server/chunks/02nj_server_app_api_projects_[projectId]_knowledge_upload_route_actions_0v4tt1t.js")
R.m(718805)
module.exports=R.m(718805).exports
