module.exports=[311447,e=>{"use strict";var t=e.i(254799),r=e.i(921284),i=e.i(824675);async function a(e){try{let a,n=e.kind||"fact",s=e.fact.trim(),o=await (0,r.get)(`SELECT id FROM memory_facts
       WHERE user_id = ? AND project_id = ? AND kind = ?
         AND LOWER(fact) = LOWER(?) AND reviewed_state != 'rejected'`,e.userId,e.projectId,n,s),c=e.sources&&e.sources.length>0?e.sources:null;if(o)await (0,r.run)(`UPDATE memory_facts
         SET updated_at = CURRENT_TIMESTAMP, sources = COALESCE(?, sources)
         WHERE id = ?`,c,o.id),a=o.id;else{a=t.default.randomUUID();let i=e.reviewedState??"applied";await (0,r.run)(`INSERT INTO memory_facts
           (id, user_id, project_id, fact, kind, source_type, source_id, reviewed_state, sources)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,a,e.userId,e.projectId,s,n,e.sourceType??null,e.sourceId??null,i,c)}return await (0,i.recordEvent)({userId:e.userId,projectId:e.projectId,eventType:"fact_recorded",payload:{factId:a,kind:n,preview:s.slice(0,120)}}),a}catch(e){return console.warn("[memory/facts] recordFact failed:",e),""}}async function n(e,t,i={}){let{limit:a=20,states:s=["applied"],kinds:o,includeSources:c}=i,u=["user_id = ?","project_id = ?"],l=[e,t];s.length>0&&(u.push(`reviewed_state IN (${s.map(()=>"?").join(",")})`),l.push(...s)),o&&o.length>0&&(u.push(`kind IN (${o.map(()=>"?").join(",")})`),l.push(...o));let d=`SELECT id, user_id, project_id, fact, kind, source_type, source_id,
                      reviewed_state, created_at, updated_at${c?", sources":""}
               FROM memory_facts
               WHERE ${u.join(" AND ")}
               ORDER BY updated_at DESC
               LIMIT ?`;return l.push(a),await (0,r.query)(d,...l)}e.s(["listFacts",0,n,"recordFact",0,a])},802062,e=>{"use strict";let t=["general","product","pricing","distribution","marketing","competitive_advantage","criticality"],r=[{re:/(price|pricing|cost|plan|tier|fee|subscription|€|\$)/i,cat:"pricing"},{re:/(channel|distribution|gtm|go.to.market|sales|partnership)/i,cat:"distribution"},{re:/(market|brand|positioning|messaging|audience|campaign|seo|content)/i,cat:"marketing"},{re:/(advantage|differentiat|moat|edge|unique|defensib|strength)/i,cat:"competitive_advantage"},{re:/(risk|threat|critical|severity|weakness|danger)/i,cat:"criticality"},{re:/(product|feature|capabilit|tech|integration|ux|platform)/i,cat:"product"}];function i(e){for(let{re:t,cat:i}of r)if(t.test(e))return i;return"general"}e.s(["COMPETITOR_CATEGORIES",0,t,"categoryForColumn",0,i,"normalizeCategory",0,function(e){let r=(e||"").trim().toLowerCase().replace(/\s+/g,"_");return t.includes(r)?r:["competitive_edge","advantage","advantages","moat","differentiation","differentiator"].includes(r)?"competitive_advantage":["price","prices","cost","plans"].includes(r)?"pricing":["gtm","channel","channels","go_to_market","sales"].includes(r)?"distribution":["risk","threat","criticality_level","severity"].includes(r)?"criticality":i(e)}])},875581,e=>{"use strict";var t=e.i(921284),r=e.i(520378),i=e.i(941171),a=e.i(802062);async function n(e,i,n,s){let o=new Map;for(let[e,t]of Object.entries(n)){let r="string"==typeof t?t.trim():null!=t?String(t).trim():"";if(!r||"—"===r)continue;let i=(0,a.categoryForColumn)(e),n=o.get(i)??[];n.push(`${e}: ${r}`),o.set(i,n)}let c=s&&s.length>0?s:null,u=0;for(let[a,n]of o)try{await (0,t.run)(`INSERT INTO competitor_categories (id, project_id, competitor_node_id, category, detail, sources)
         VALUES (?, ?, ?, ?, ?, ?)
         ON CONFLICT (competitor_node_id, category) DO UPDATE SET
           detail = EXCLUDED.detail,
           sources = COALESCE(EXCLUDED.sources, competitor_categories.sources),
           updated_at = CURRENT_TIMESTAMP`,(0,r.generateId)("ccat"),e,i,a,n.join("; ").slice(0,1500),c),u++}catch(e){console.warn("[competitor-categories] upsert failed (non-fatal):",e.message)}return u}async function s(e){let r=await (0,t.query)(`SELECT id, name, summary, reviewed_state
       FROM graph_nodes
      WHERE project_id = ? AND node_type = 'competitor'
        AND reviewed_state IN ('applied', 'pending')
      ORDER BY CASE reviewed_state WHEN 'applied' THEN 0 ELSE 1 END, name`,e);if(0===r.length)return[];let n=await (0,t.query)(`SELECT competitor_node_id, category, detail, sources
       FROM competitor_categories WHERE project_id = ?`,e),s=e=>{let t=a.COMPETITOR_CATEGORIES.indexOf(e);return -1===t?a.COMPETITOR_CATEGORIES.length:t},o=new Map;for(let e of n){let t=o.get(e.competitor_node_id)??[];t.push({category:e.category,detail:e.detail,sources:(()=>{let t=(0,i.coerceJson)(e.sources);return Array.isArray(t)?t:null})()}),o.set(e.competitor_node_id,t)}for(let e of o.values())e.sort((e,t)=>s(e.category)-s(t.category));return r.map(e=>({id:e.id,name:e.name,summary:e.summary,reviewed_state:e.reviewed_state,categories:o.get(e.id)??[]}))}async function o(e,i,a,n){let s=i.trim();if(!s)return;let o=await (0,t.get)("SELECT id FROM graph_nodes WHERE project_id = ? AND LOWER(name) = LOWER(?) LIMIT 1",e,s);if(o)return await (0,t.run)("UPDATE graph_nodes SET summary = COALESCE(NULLIF(?, ''), summary), sources = COALESCE(?, sources) WHERE id = ?",a,n,o.id),o.id;let c=(0,r.generateId)("gnode");return await (0,t.run)(`INSERT INTO graph_nodes (id, project_id, name, node_type, summary, sources, reviewed_state)
     VALUES (?, ?, ?, 'competitor', ?, ?, 'pending')`,c,e,s,a,n),c}async function c(e,i,n,s){let o=s&&s.length>0?s:null,c=0;for(let s of n){let n=(s.detail||"").trim();if(n)try{await (0,t.run)(`INSERT INTO competitor_categories (id, project_id, competitor_node_id, category, detail, sources)
         VALUES (?, ?, ?, ?, ?, ?)
         ON CONFLICT (competitor_node_id, category) DO UPDATE SET
           detail = EXCLUDED.detail,
           sources = COALESCE(EXCLUDED.sources, competitor_categories.sources),
           updated_at = CURRENT_TIMESTAMP`,(0,r.generateId)("ccat"),e,i,(0,a.normalizeCategory)(s.category),n.slice(0,1500),o),c++}catch(e){console.warn("[competitor-categories] setCompetitorCategories failed (non-fatal):",e.message)}}return c}async function u(e,t){let r=t.sources&&t.sources.length>0?t.sources:null,i=await o(e,t.name,(t.summary||"").slice(0,500),r);if(!i)return{categories:0};let a=await c(e,i,t.categories||[],t.sources);return{nodeId:i,categories:a}}e.s(["persistCompetitorAnalysis",0,u,"persistCompetitorCategories",0,n,"readCompetitorMatryoshka",0,s])},390472,e=>{"use strict";var t=e.i(522734),r=e.i(814747),i=e.i(581507);let a=(0,r.join)(process.cwd(),"agents"),n=(0,r.join)(process.cwd(),"launchpad-skills"),s=new Map;function o(e,a,n){for(let o of[n!==i.DEFAULT_LOCALE?(0,r.join)(e,`${a}.${n}.md`):null,(0,r.join)(e,`${a}.md`)].filter(e=>null!==e)){if(s.has(o)){let e=s.get(o);if(e)return e;continue}if((0,t.existsSync)(o)){let e=(0,t.readFileSync)(o,"utf-8");return s.set(o,e),e}s.set(o,"")}return null}function c(e){if(e===i.DEFAULT_LOCALE)return null;let t=i.LOCALE_ENGLISH_NAME[e];return`## Language
Always write every founder-facing word — chat replies AND the prose inside artifacts — in ${t}.
Stay in ${t} for the entire conversation, even if earlier turns were in another language.
Do NOT translate: brand/product names, people's names, code, URLs, or the structured field *keys* inside :::artifact blocks (only their human-readable values).`}async function u(e,t){let r=await t("SELECT locale FROM projects WHERE id = ?",e);return r[0]?.locale==="it"?"it":"en"}e.s(["buildSystemPromptString",0,function(e={}){return function(e={}){let t=(0,i.asLocale)(e.locale),s=e.context||"chat",u=[],l=o(a,"SOUL",t);l&&u.push(l);let d=o(a,"AGENTS",t);if(d&&u.push(d),"cron"===s||"monitor"===s){let e=o(a,"HEARTBEAT",t);e&&u.push(e)}if(e.activeSkillId){var E;let i=(E=e.activeSkillId,o((0,r.join)(n,E),"SKILL",t));i&&u.push(i)}let _=c(t);_&&u.push(_);let p=u.join("\n\n---\n\n"),m=[];e.tail&&m.push(e.tail),e.projectContext&&m.push(e.projectContext);let f=m.join("\n\n");return{staticPrefix:p,dynamicTail:f,full:f?`${p}

---

${f}`:p,staticTokensEstimate:Math.ceil(p.length/4)}}(e).full},"languageDirective",0,c,"resolveProjectLocale",0,u])},117726,e=>{"use strict";var t=e.i(921284);let r=e=>{if(!Array.isArray(e))return null;let t=e.filter(e=>"string"==typeof e&&e.trim().length>0).map(e=>e.trim().slice(0,300)).slice(0,12);return t.length?t:null};async function i(e,i){let a={unfair_advantage:(e=>{if("string"!=typeof e)return null;let t=e.trim().slice(0,1200);return t.length?t:null})(i.unfair_advantage),key_metrics:r(i.key_metrics),revenue_streams:r(i.revenue_streams),cost_structure:r(i.cost_structure)};if(null==a.unfair_advantage&&null==a.key_metrics&&null==a.revenue_streams&&null==a.cost_structure)return[];await (0,t.run)(`INSERT INTO idea_canvas (project_id, unfair_advantage, key_metrics, revenue_streams, cost_structure)
     VALUES (?, ?, ?, ?, ?)
     ON CONFLICT (project_id) DO UPDATE SET
       unfair_advantage = COALESCE(NULLIF(EXCLUDED.unfair_advantage, ''), idea_canvas.unfair_advantage),
       key_metrics     = CASE WHEN jsonb_typeof(EXCLUDED.key_metrics)     = 'array' AND jsonb_array_length(EXCLUDED.key_metrics)     > 0 THEN EXCLUDED.key_metrics     ELSE idea_canvas.key_metrics     END,
       revenue_streams = CASE WHEN jsonb_typeof(EXCLUDED.revenue_streams) = 'array' AND jsonb_array_length(EXCLUDED.revenue_streams) > 0 THEN EXCLUDED.revenue_streams ELSE idea_canvas.revenue_streams END,
       cost_structure  = CASE WHEN jsonb_typeof(EXCLUDED.cost_structure)  = 'array' AND jsonb_array_length(EXCLUDED.cost_structure)  > 0 THEN EXCLUDED.cost_structure  ELSE idea_canvas.cost_structure  END`,e,a.unfair_advantage,a.key_metrics??null,a.revenue_streams??null,a.cost_structure??null);let n=[];return null!=a.unfair_advantage&&n.push("unfair_advantage"),null!=a.key_metrics&&n.push("key_metrics"),null!=a.revenue_streams&&n.push("revenue_streams"),null!=a.cost_structure&&n.push("cost_structure"),n}e.s(["persistCanvasDetails",0,i])},721518,e=>{"use strict";var t=e.i(921284),r=e.i(520378);async function i(e,i,a,n){if(Number.isFinite(i)&&!(i<=0))try{let s=await (0,t.get)("SELECT overall_score FROM score_history WHERE project_id = ? ORDER BY created_at DESC LIMIT 1",e);if(s&&Math.round(100*s.overall_score)===Math.round(100*i))return;await (0,t.run)(`INSERT INTO score_history (id, project_id, overall_score, recommendation, source)
       VALUES (?, ?, ?, ?, ?)`,(0,r.generateId)("sch"),e,i,n??null,a)}catch(e){console.warn("[score-history] append failed (non-fatal):",e.message)}}async function a(e,r=50){try{return await (0,t.query)(`SELECT overall_score, recommendation, source, created_at
         FROM score_history WHERE project_id = ?
        ORDER BY created_at ASC LIMIT ?`,e,r)}catch{return[]}}e.s(["getScoreHistory",0,a,"recordScoreHistory",0,i])},815789,e=>{"use strict";function t(e){if("number"==typeof e)return Number.isFinite(e)?e:null;if("string"!=typeof e)return null;let t=e.replace(/[,$€£¥~≈]/g,"").match(/(-?\d+(?:\.\d+)?)\s*(k|thousand|mm|mn|m|million|bn|b|billion|tn|t|trillion)?/i);if(!t)return null;let r=parseFloat(t[1]);if(!Number.isFinite(r))return null;let i=(t[2]||"").toLowerCase();return r*("k"===i||"thousand"===i?1e3:"m"===i||"mm"===i||"mn"===i||"million"===i?1e6:"b"===i||"bn"===i||"billion"===i?1e9:"t"===i||"tn"===i||"trillion"===i?1e12:1)}function r(e,r){let i=e?.[r];return null==i?null:"string"==typeof i||"number"==typeof i?t(i):"object"==typeof i?t(i.estimate??i.value):null}let i=["TAM","SAM","SOM"];e.s(["fmtAmount",0,function(e){let t=Math.abs(e);return t>=1e9?`$${(e/1e9).toFixed(2)}B`:t>=1e6?`$${(e/1e6).toFixed(1)}M`:t>=1e3?`$${(e/1e3).toFixed(0)}K`:`$${e}`},"marketSizeDrift",0,function(e,t,a=.2){if(!e||!t||"object"!=typeof e||"object"!=typeof t)return null;let n=null;for(let s of i){let i=s.toLowerCase(),o=r(e,i),c=r(t,i);if(null==o||null==c||0===o)continue;let u=Math.abs(c-o)/Math.abs(o);u>a&&(!n||u>n.deltaPct)&&(n={metric:s,oldAmount:o,newAmount:c,deltaPct:u})}return n},"parseAmount",0,t])}];

//# sourceMappingURL=tech-bricks_LaunchPad-v2_src_lib_0sw17e9._.js.map