// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/demo/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/chat">> = Specific
  const handler = {} as typeof import("../../src/app/demo/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/financial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/financial">> = Specific
  const handler = {} as typeof import("../../src/app/demo/financial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/inbox">> = Specific
  const handler = {} as typeof import("../../src/app/demo/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/demo/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../src/app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/onboard/[partnerSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboard/[partnerSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/onboard/[partnerSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/actions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/actions">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/actions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/assumptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/assumptions">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/assumptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/chat">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/financial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/financial">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/financial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/monitors/[monitorId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/monitors/[monitorId]">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/monitors/[monitorId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/monitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/monitors">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/monitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/signals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/signals">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/signals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/today/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/today">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/today/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[projectId]/usage">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/hook/send-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/hook/send-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/hook/send-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/credits/recharge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits/recharge">> = Specific
  const handler = {} as typeof import("../../src/app/api/credits/recharge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cron/run-monitor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/run-monitor">> = Specific
  const handler = {} as typeof import("../../src/app/api/cron/run-monitor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/cronbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cronbeat">> = Specific
  const handler = {} as typeof import("../../src/app/api/cronbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[projectId]/alerts/[alertId]/dismiss/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[projectId]/alerts/[alertId]/dismiss">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[projectId]/alerts/[alertId]/dismiss/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[projectId]/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[projectId]/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[projectId]/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[projectId]/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[projectId]/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[projectId]/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[projectId]/burn-rate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[projectId]/burn-rate">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[projectId]/burn-rate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[projectId]/metrics/[metricId]/entry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[projectId]/metrics/[metricId]/entry">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[projectId]/metrics/[metricId]/entry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[projectId]/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[projectId]/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[projectId]/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/dev-projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev-projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/dev-projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/investors/[investorId]/interaction/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/investors/[investorId]/interaction">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/investors/[investorId]/interaction/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/investors/[investorId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/investors/[investorId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/investors/[investorId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/investors/[investorId]/stage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/investors/[investorId]/stage">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/investors/[investorId]/stage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/investors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/investors">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/investors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/pitch/iterate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/pitch/iterate">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/pitch/iterate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/prepare-update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/prepare-update">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/prepare-update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/round/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/round">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/round/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/term-sheets/[tsId]/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/term-sheets/[tsId]/analyze">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/term-sheets/[tsId]/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundraising/[projectId]/term-sheets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundraising/[projectId]/term-sheets">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundraising/[projectId]/term-sheets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/graph/[projectId]/edges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/[projectId]/edges">> = Specific
  const handler = {} as typeof import("../../src/app/api/graph/[projectId]/edges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/graph/[projectId]/nodes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/[projectId]/nodes">> = Specific
  const handler = {} as typeof import("../../src/app/api/graph/[projectId]/nodes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/graph/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/graph/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/graph/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/growth/[projectId]/loops/[loopId]/iterate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth/[projectId]/loops/[loopId]/iterate">> = Specific
  const handler = {} as typeof import("../../src/app/api/growth/[projectId]/loops/[loopId]/iterate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/growth/[projectId]/loops/[loopId]/iterations/[iterId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth/[projectId]/loops/[loopId]/iterations/[iterId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/growth/[projectId]/loops/[loopId]/iterations/[iterId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/growth/[projectId]/loops/[loopId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth/[projectId]/loops/[loopId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/growth/[projectId]/loops/[loopId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/growth/[projectId]/loops/[loopId]/synthesize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth/[projectId]/loops/[loopId]/synthesize">> = Specific
  const handler = {} as typeof import("../../src/app/api/growth/[projectId]/loops/[loopId]/synthesize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/growth/[projectId]/loops/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/growth/[projectId]/loops">> = Specific
  const handler = {} as typeof import("../../src/app/api/growth/[projectId]/loops/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/journey/[projectId]/milestones/[msId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/journey/[projectId]/milestones/[msId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/journey/[projectId]/milestones/[msId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/journey/[projectId]/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/journey/[projectId]/update">> = Specific
  const handler = {} as typeof import("../../src/app/api/journey/[projectId]/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/partner-configs/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/partner-configs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/partner-configs/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/preview-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/preview-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/actions/[actionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/actions/[actionId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/actions/[actionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/actions">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/brief/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/brief">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/brief/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/competitors/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/competitors/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/competitors/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/competitors/breakdown/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/competitors/breakdown">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/competitors/breakdown/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/competitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/competitors">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/competitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/context-export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/context-export">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/context-export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/context/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/context">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/context/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/credits">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/data-room/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/data-room/[itemId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/data-room/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/data-room/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/data-room">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/data-room/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/financial-model/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/financial-model">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/financial-model/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/idea-canvas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/idea-canvas">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/idea-canvas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/intelligence-briefs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/intelligence-briefs">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/intelligence-briefs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/intelligence/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/intelligence/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/intelligence/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/interviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/interviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/interviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/knowledge-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/knowledge-count">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/knowledge-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/knowledge/[itemId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/knowledge/[itemId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/knowledge/[itemId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/knowledge/apply-batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/knowledge/apply-batch">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/knowledge/apply-batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/knowledge/digest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/knowledge/digest">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/knowledge/digest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/knowledge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/knowledge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/knowledge/unified/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/knowledge/unified">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/knowledge/unified/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/knowledge/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/knowledge/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/knowledge/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/loops/[loopId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/loops/[loopId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/loops/[loopId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/loops/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/loops">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/loops/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/members/[memberId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/members/[memberId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/members/[memberId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/members">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/monitor-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/monitor-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/monitor-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/monitors/[monitorId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/monitors/[monitorId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/monitors/[monitorId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/monitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/monitors">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/monitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/node-importance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/node-importance">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/node-importance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/notes">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/recent-moves/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/recent-moves">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/recent-moves/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/score-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/score-history">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/score-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/score">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/signal-activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/signal-activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/signal-activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/skills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/skills">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/skills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/stages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/stages">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/stages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/step/[stepName]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/step/[stepName]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/step/[stepName]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/tasks/[clientArtifactId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/tasks/[clientArtifactId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/tasks/[clientArtifactId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/timeline">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/usage/groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/usage/groups">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/usage/groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/usage">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/validation/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/validation/commit">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/validation/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/watch-sources/[sourceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/watch-sources/[sourceId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/watch-sources/[sourceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/watch-sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/watch-sources">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/watch-sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/[projectId]/watchers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[projectId]/watchers">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/[projectId]/watchers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/risk-analysis/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/risk-analysis/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/risk-analysis/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tasks/[taskId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks/[taskId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tasks/[taskId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/api-keys">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/[projectId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/[projectId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/demo/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../src/app/demo/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/project/[projectId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/project/[projectId]">> = Specific
  const handler = {} as typeof import("../../src/app/project/[projectId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
