var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/credits/route.js")
R.c("server/chunks/[root-of-the-server]__0rtumru._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0mgx._s._.js")
R.c("server/chunks/11xl_next-internal_server_app_api_projects_[projectId]_credits_route_actions_0xsiba2.js")
R.m(235438)
module.exports=R.m(235438).exports
