var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/loops/[loopId]/route.js")
R.c("server/chunks/[root-of-the-server]__11p08xu._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0c_d7i~._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_journey_0~y2qc1._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0k6s59l._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_071t7sf._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/02nj_server_app_api_projects_[projectId]_loops_[loopId]_route_actions_0cmkftz.js")
R.m(206471)
module.exports=R.m(206471).exports
