var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/dashboard/[projectId]/analyze/route.js")
R.c("server/chunks/[root-of-the-server]__0fday9u._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_llm_0plha9m._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/0mjv_0yf2dbb._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0_yadel._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/02nj_server_app_api_dashboard_[projectId]_analyze_route_actions_0t0euey.js")
R.m(20877)
module.exports=R.m(20877).exports
