var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/stages/route.js")
R.c("server/chunks/[root-of-the-server]__0b3oqek._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_journey_0~y2qc1._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/0d7q__next-internal_server_app_api_projects_[projectId]_stages_route_actions_100qo.g.js")
R.m(694843)
module.exports=R.m(694843).exports
