#!/usr/bin/env bash
set -euo pipefail

# ── SenseFound Deploy Script ─────────────────────────────────────────
# Builds locally via the Netlify CLI (includes OpenNext adapter
# post-processing for SSR functions + edge middleware), then uploads
# the built output directly to Netlify production.
#
# Usage:
#   ./scripts/deploy.sh                    # Build + deploy to production
#   ./scripts/deploy.sh --dry-run          # Build only, don't deploy
#   ./scripts/deploy.sh --preview          # Deploy to a preview URL (not prod)
#   ./scripts/deploy.sh --force            # Skip the up-to-date-with-main guard
#
# Prerequisites:
#   npx netlify-cli login   (authenticate as start@sensefound.io / Launchpad team)
# ─────────────────────────────────────────────────────────────────────

DRY_RUN=false
PREVIEW=false
FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)  DRY_RUN=true; shift ;;
    --preview)  PREVIEW=true; shift ;;
    --force)    FORCE=true; shift ;;
    *)          shift ;;
  esac
done

# ── Freshness guard (prod deploys only) ──────────────────────────────
# A prod deploy must ship exactly what's on origin/main. On 2026-07-22 a
# routinely-dirty next-env.d.ts made `git pull --ff-only` fail; because the
# caller piped the pull through `tail`, the failure was masked and the deploy
# ran on a STALE HEAD — prod served an old build for hours while every deploy
# reported success. This guard makes that impossible: reset the autogenerated
# file (it has no deploy impact and only blocks the pull), then refuse to ship
# a checkout that isn't on the latest main. --force is the escape hatch.
if [ "$DRY_RUN" = false ] && [ "$PREVIEW" = false ]; then
  if ! git diff --quiet -- next-env.d.ts 2>/dev/null; then
    echo "▸ Resetting autogenerated next-env.d.ts (blocks the pull, no deploy impact)"
    git checkout -- next-env.d.ts 2>/dev/null || true
  fi

  echo "▸ Verifying the checkout is on the latest origin/main…"
  git fetch origin main --quiet 2>/dev/null || echo "  (warning: git fetch failed — proceeding without the remote check)"
  DIRTY="$(git status --porcelain --untracked-files=no)"
  LOCAL="$(git rev-parse HEAD)"
  REMOTE="$(git rev-parse origin/main 2>/dev/null || echo "")"

  if [ -n "$DIRTY" ]; then
    echo "✗ Working tree has uncommitted tracked changes:"
    git status --short --untracked-files=no
    if [ "$FORCE" != true ]; then
      echo "  Refusing to deploy a modified checkout. Commit/stash first, or pass --force."
      exit 1
    fi
  fi
  if [ -n "$REMOTE" ] && [ "$LOCAL" != "$REMOTE" ]; then
    echo "✗ HEAD ($(git rev-parse --short HEAD)) is not origin/main ($(git rev-parse --short origin/main))."
    echo "  The checkout is behind — a STALE build would ship (the 2026-07-22 footgun)."
    echo "  Fix: git pull --ff-only origin main   then re-run deploy (or pass --force)."
    if [ "$FORCE" != true ]; then
      exit 1
    fi
  fi
  echo "✓ On origin/main ($(git rev-parse --short HEAD))."
fi

echo "▸ Building locally with Netlify CLI (Next.js + OpenNext adapter)…"
npx netlify-cli build

if [ "$DRY_RUN" = true ]; then
  echo "✓ Build passed. Dry run — skipping deploy."
  exit 0
fi

if [ "$PREVIEW" = true ]; then
  echo "▸ Deploying to preview URL…"
  npx netlify-cli deploy
else
  echo "▸ Deploying to production…"
  npx netlify-cli deploy --prod
fi

echo ""
echo "✓ Deploy complete."
echo "  Site: https://launchpad.sensefound.io"
echo "  Logs: https://app.netlify.com/projects/lustrous-bavarois-a2a86b/deploys"
