var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/fundraising/[projectId]/prepare-update/route.js")
R.c("server/chunks/[root-of-the-server]__0n-7fve._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_llm_0plha9m._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/0mjv_0yf2dbb._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0_yadel._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/02nj_server_app_api_fundraising_[projectId]_prepare-update_route_actions_0pvbiu7.js")
R.m(201557)
module.exports=R.m(201557).exports
