var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/projects/[projectId]/loops/route.js")
R.c("server/chunks/[root-of-the-server]__0~s.t2e._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0c_d7i~._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_journey_0~y2qc1._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_0k6s59l._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_0ungsfv._.js")
R.c("server/chunks/[root-of-the-server]__0xbhf.g._.js")
R.c("server/chunks/0mjv_next_07jphsx._.js")
R.c("server/chunks/tech-bricks_LaunchPad-v2_src_lib_071t7sf._.js")
R.c("server/chunks/[root-of-the-server]__0u8uxfm._.js")
R.c("server/chunks/0d7q__next-internal_server_app_api_projects_[projectId]_loops_route_actions_06nu3y9.js")
R.m(698219)
module.exports=R.m(698219).exports
